name: Tagger
author: JRoy
version: 1.0
api-version: 1.14
main: io.github.jroy.tagger.Tagger
depend: [PluginLibrary, Stonks, Vault]
commands:
  tags:
    description: Main command for Tag plugin
    usage: /tags